---
- name: learning ansible
  hosts: target
  gather_facts: yes
  become: yes

  vars:
    default_name: "sagar"
    sample_name: "salmman"
  roles:
  - httpd_uninstall
  - httpd_install
  tasks:
  - name: trying handlers
    yum:
      name: telnet
      state: present
    notify: telnet user

  handlers:
  - name: telnet user
    debug:
      msg: "the {{ sample_name }} user install telnet "
